version: '3.9'

services:
  postgres-supercassa:
    image: postgres
    container_name: postgres-supercassa
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql